---
description: "#{repo}"
builds:
- platform: "alpine"
  arch: "amd64"
  asset_filename: "monitoring-plugins-alpine_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'alpine'"
  - "entity.system.arch == 'amd64'"

- platform: "amazon2"
  arch: "amd64"
  asset_filename: "monitoring-plugins-amazon2_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'amazon'"
  - "entity.system.platform_version == '2'"
  - "entity.system.arch == 'amd64'"

- platform: "amazon2023"
  arch: "amd64"
  asset_filename: "monitoring-plugins-amazon2023_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'amazon'"
  - "entity.system.platform_version == '2023'"
  - "entity.system.arch == 'amd64'"

- platform: "centos7"
  arch: "amd64"
  asset_filename: "monitoring-plugins-centos7_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'rhel'"
  - "entity.system.platform_version.split('.')[0] == '7'"
  - "entity.system.arch == 'amd64'"

- platform: "centos8"
  arch: "amd64"
  asset_filename: "monitoring-plugins-centos8_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'rhel'"
  - "entity.system.platform_version.split('.')[0] == '8'"
  - "entity.system.arch == 'amd64'"

- platform: "rocky9"
  arch: "amd64"
  asset_filename: "monitoring-plugins-rocky9_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'rhel'"
  - "entity.system.platform_version.split('.')[0] == '9'"
  - "entity.system.arch == 'amd64'"

- platform: "debian10"
  arch: "amd64"
  asset_filename: "monitoring-plugins-debian10_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'debian'"
  - "entity.system.platform_version.split('.')[0] == '10'"
  - "entity.system.arch == 'amd64'"

- platform: "debian11"
  arch: "amd64"
  asset_filename: "monitoring-plugins-debian11_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform_family == 'debian'"
  - "entity.system.platform_version.split('.')[0] == '11'"
  - "entity.system.arch == 'amd64'"

- platform: "ubuntu1404"
  arch: "amd64"
  asset_filename: "monitoring-plugins-ubuntu1404_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'ubuntu'"
  - "entity.system.platform_version.split('.')[0] == '14'"
  - "entity.system.arch == 'amd64'"

- platform: "ubuntu1604"
  arch: "amd64"
  asset_filename: "monitoring-plugins-ubuntu1604_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'ubuntu'"
  - "entity.system.platform_version.split('.')[0] == '16'"
  - "entity.system.arch == 'amd64'"

- platform: "ubuntu1804"
  arch: "amd64"
  asset_filename: "monitoring-plugins-ubuntu1804_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'ubuntu'"
  - "entity.system.platform_version.split('.')[0] == '18'"
  - "entity.system.arch == 'amd64'"

- platform: "ubuntu2004"
  arch: "amd64"
  asset_filename: "monitoring-plugins-ubuntu2004_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'ubuntu'"
  - "entity.system.platform_version.split('.')[0] == '20'"
  - "entity.system.arch == 'amd64'"

- platform: "ubuntu2204"
  arch: "amd64"
  asset_filename: "monitoring-plugins-ubuntu2204_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'ubuntu'"
  - "entity.system.platform_version.split('.')[0] == '22'"
  - "entity.system.arch == 'amd64'"

- platform: "raspberrypi64"
  arch: "arm64"
  asset_filename: "monitoring-plugins-raspberrypi64_#{version}_linux_arm64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'debian'"
  - "entity.system.platform_version.split('.')[0] == '11'"
  - "entity.system.arch == 'arm64'"

- platform: "xcp-ng8"
  arch: "amd64"
  asset_filename: "monitoring-plugins-centos7_#{version}_linux_amd64.tar.gz"
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  filter:
  - "entity.system.os == 'linux'"
  - "entity.system.platform == 'xcp-ng'"
  - "entity.system.platform_version.split('.')[0] == '8'"
  - "entity.system.arch == 'amd64'"
