# https://discourse.sensu.io/t/heads-up-new-feature-in-bonsai-for-asset-developers/2866
name: Bonsai Request Rebuild

on:
  workflow_run:
    workflows:
      - Publish
    types:
      - completed

jobs:
  bonsai-build:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: request bonsai rebuild
        run: >
          curl -v -XPOST
          -H "X-GitHub-Token: ${{ secrets.BONSAI_GITHUB_TOKEN }}"
          --url "https://bonsai.sensu.io/assets/${{ github.repository }}/build"
